### ISSUE TITLE
libsmbd-base-samba4.so not found

### ISSUE THREAD

**Issue by wyznerd** [gboudreau/Greyhole#180] opened 2017-07-19 21:02 UTC
Brand new install on Ubuntu 17.04 can't mount shares due to vfs issues.

```
[2017/07/19 15:52:34.537790,  0] ../lib/util/modules.c:48(load_module)
  Error loading module '/usr/lib/x86_64-linux-gnu/samba/vfs/greyhole.so': libsmbd-base-samba4.so: cannot open shared object file: No such file or directory
[2017/07/19 15:52:34.537806,  0] ../source3/smbd/vfs.c:184(vfs_init_custom)
  error probing vfs module 'greyhole': NT_STATUS_UNSUCCESSFUL
[2017/07/19 15:52:34.537820,  0] ../source3/smbd/vfs.c:379(smbd_vfs_init)
  smbd_vfs_init: vfs_init_custom failed for greyhole
[2017/07/19 15:52:34.537825,  0] ../source3/smbd/service.c:604(make_connection_snum)
```

libsmbd-base-samb4.so is found in `/lib/x86_x64/samba/`

Ive followed along with the other bug reports that supposedly fixed this issue and no combination of symlinks seem to be fixing it for this one.

*Ubuntu 17.04*
*Samba 4.5.8*
*Greyhole 0.10.11*

**Comment by gboudreau** [comment] 2017-07-19 22:51
Is `/usr/lib/x86_64-linux-gnu/samba/` and `/lib/x86_x64/samba/` the same folder?

Since the greyhole.so is in `/usr/lib/x86_64-linux-gnu`, my guess is that the libsmbd-base-samba4.so library is expected to be in `/usr/lib/x86_64-linux-gnu/samba`.

**Comment by gboudreau** [comment] 2017-07-19 22:52
My greyhole.so is here:
`/usr/lib/x86_64-linux-gnu/samba/vfs/greyhole.so`
and by libsmbd-base-samba4.so is here:
`/usr/lib/x86_64-linux-gnu/samba/libsmbd-base-samba4.so`
i.e. in the same samba lib folder.

**Comment by gboudreau** [comment] 2017-07-19 23:02
You can also try to add the `/lib/x86_x64/samba` folder to the ldconfig paths:
```
echo "/lib/x86_x64/samba" | sudo tee /etc/ld.so.conf.d/greyhole.conf
```

The goal is that ldconfig can see the required libsmbd-base-samba4.so file:
```
sudo ldconfig -v | grep libsmbd-base
```

**Comment by gboudreau** [comment] 2017-07-19 23:23
I was able to reproduce your issue, and the above commands to add `/lib/x86_x64/samba` to ldconfig path fixed it.
I added a `sudo ldconfig` in the above comment, since that is needed when one updated the ldconfig config(!)

**Comment by gaspardleon** [comment] 2017-07-20 10:35
I'm facing a similar issue  under Debian Stretch (9)

`libsmbd-base-samba4.so => not found`
`libsamba-debug-samba4.so => not found`

Should I open a new issue or describe it here?
It appears the correct symlinks are in place... I've tried altering ld config etc

**Comment by gboudreau** [comment] 2017-07-20 11:25
I am using Debian 9, and fixed it like I explained. Just the lib directory is different:
```
echo "/usr/lib/x86_64-linux-gnu/samba" | sudo tee /etc/ld.so.conf.d/greyhole.conf
sudo ldconfig
ldd /usr/lib/x86_64-linux-gnu/samba/vfs/greyhole.so | grep libsmbd-base-samba4
```

**Comment by gboudreau** [comment] 2017-07-20 12:12
You can just install 0.10.12; it should take care of that for you, and will ensure it is using the right path to the samba lib dir.

**Comment by gaspardleon** [comment] 2017-07-20 13:03
thanks for that, already tried that but I'll give it another try tomorrow - it's late and I shut the machine down

**Comment by gaspardleon** [comment] 2017-07-23 11:21
So I followed the website instructions and got 0.10.11-1
So I just uninstalled that.

Now I'm installing again ... hopefully it will install 0.10.12 by itself... if not do I need to compile it myself?

Cheers

**Comment by gboudreau** [comment] 2017-07-23 11:31
`apt-get update`

**Comment by gaspardleon** [comment] 2017-07-23 12:23
don't worry I'm using MHDDFS now, thanks for your quick assistance

**Comment by dedge** [comment] 2017-08-01 18:50
Hello, I did a fresh install of Debian 9.1 and am running Greyhole 0.10.12 and have experienced the same issue.  Doing a ldd of greyhole.so shows that it can't find libsmbd-base-samba4.so or libsamba-debug-samba4.so.  Trying the method posted earlier with ldconfig did not help either.

As a quick workaround I did a symbolic link for the two files in /usr/lib which appears to work successfully.

**Comment by gboudreau** [comment] 2017-10-01 17:34
I was able to reproduce this problem. Will fix.

**Comment by gboudreau** [comment] 2017-10-01 17:37
Fixed in db88fb3b2c618c971f960636fcc8e48463f78ef0 (included in 0.10.13)

**Closed by gboudreau** 2017-10-01 17:37 UTC

**Comment by robojerk** [comment] 2023-01-07 22:42
I'm having a similiar issue in Ubuntu 22.10

I tried `echo "/lib/x86_x64/samba" | sudo tee /etc/ld.so.conf.d/greyhole.conf
sudo ldconfig` but not getting anywhere...

```
echo "/lib/x86_x64/samba" | sudo tee /etc/ld.so.conf.d/greyhole.conf
/lib/x86_x64/samba

echo "/usr/lib/x86_64-linux-gnu/samba" | sudo tee /etc/ld.so.conf.d/greyhole.conf
sudo ldconfig
ldd /usr/lib/x86_64-linux-gnu/samba/vfs/greyhole.so | grep libsmbd-base-samba4
/usr/lib/x86_64-linux-gnu/samba
        libsmbd-base-samba4.so => /usr/share/greyhole/vfs-build/samba-4.16.4/bin/shared/private/libsmbd-base-samba4.so (0x00007f2090600000)
```

My error when installing the latest version
```
sudo dpkg -i greyhole/greyhole_0.15.18-1_amd64.deb 
(Reading database ... 202062 files and directories currently installed.)
Preparing to unpack .../greyhole_0.15.18-1_amd64.deb ...
Unpacking greyhole (0.15.18-1) over (0.15.18-1) ...
Setting up greyhole (0.15.18-1) ...
Detected custom (locally-compiled) Greyhole VFS module at /usr/lib/x86_64-linux-gnu/samba/vfs/greyhole.so; will NOT overwrite it.
Error: missing dependent library libsmbd-base.so.0 (libsmbd-base-samba4.so)
dpkg: error processing package greyhole (--install):
 installed greyhole package post-installation script subprocess returned error exit status 1
Processing triggers for man-db (2.10.2-2) ...
Errors were encountered while processing:
 greyhole
```

**Comment by gboudreau** [comment] 2023-01-07 23:00
@robojerk The .deb install script expects either `libsmbd-base-samba4.so` (or `libsmbd-base.so.0`) to be in the `/usr/lib/x86_64-linux-gnu/samba/` folder.
I guess creating a symlink there pointing to `/usr/share/greyhole/vfs-build/samba-4.16.4/bin/shared/private/libsmbd-base-samba4.so` would work:

```bash
sudo ln -s /usr/share/greyhole/vfs-build/samba-4.16.4/bin/shared/private/libsmbd-base-samba4.so /usr/lib/x86_64-linux-gnu/samba/libsmbd-base-samba4.so
```

**Comment by robojerk** [comment] 2023-01-07 23:13
```
sudo ln -s /usr/share/greyhole/vfs-build/samba-4.16.4/bin/shared/private/libsmbd-base-samba4.so /usr/lib/x86_64-linux-gnu/samba/libsmbd-base-samba4.so
ln: failed to create symbolic link '/usr/lib/x86_64-linux-gnu/samba/libsmbd-base-samba4.so': File exists
```

I still get the same error when installing the .deb :(

**Comment by gboudreau** [comment] 2023-01-08 13:40
[This](https://github.com/gboudreau/Greyhole/blob/master/DEBIAN/postinst) is the script in question.
Maybe try to execute it manually, section by section, until you reach the line that returns this error (L136).
Maybe `${TARGET_LIBDIR}` is not set to the right path or something. Executing the script by section will allow you to understand why it can't find the .so in question.

**Comment by robojerk** [comment] 2023-01-08 18:38
First I verified what MAJOR_SMB_VERSION is
```
MAJOR_SMB_VERSION=$(smbd --version | awk '{print $2}' | awk -F'-' '{print $1}' | awk -F'.' '{print $1}')
echo $MAJOR_SMB_VERSION
```
I get an output of 4

Then I ran this and got no errors
```
if [ "${MAJOR_SMB_VERSION}" = "4" ]; then
    if [ -f ${TARGET_LIBDIR}/samba/libsmbd_base.so.0 ]; then
        if [ ! -f ${TARGET_LIBDIR}/samba/libsmbd_base.so ]; then
            ln -s ${TARGET_LIBDIR}/samba/libsmbd_base.so.0 ${TARGET_LIBDIR}/samba/libsmbd_base.so
        fi
    # I Removed the rest of the code since it's 4
    fi
fi

```
But if I run this I get the error
```
MAJOR_SMB_VERSION=$(smbd --version | awk '{print $2}' | awk -F'-' '{print $1}' | awk -F'.' '{print $1}')
if [ "${MAJOR_SMB_VERSION}" = "4" ]; then
    if [ -f ${TARGET_LIBDIR}/samba/libsmbd_base.so.0 ]; then
        if [ ! -f ${TARGET_LIBDIR}/samba/libsmbd_base.so ]; then
            ln -s ${TARGET_LIBDIR}/samba/libsmbd_base.so.0 ${TARGET_LIBDIR}/samba/libsmbd_base.so
        fi
    else
        if [ ! -f ${TARGET_LIBDIR}/samba/libsmbd-base-samba4.so ]; then
            if [ -f ${TARGET_LIBDIR}/samba/libsmbd-base.so.0 ]; then
                ln -s ${TARGET_LIBDIR}/samba/libsmbd-base.so.0 ${TARGET_LIBDIR}/samba/libsmbd-base-samba4.so
            else
                echo "Error: missing dependent library libsmbd-base.so.0 (libsmbd-base-samba4.so)"
                exit 1
            fi
        fi
    fi
fi
Error: missing dependent library libsmbd-base.so.0 (libsmbd-base-samba4.so)
```

If I change line 131 from 
`else`
to
`elif [ "${MAJOR_SMB_VERSION}" != "4" ]; then`
I don't get an error

**Comment by gboudreau** [comment] 2023-01-08 18:46
Your suggested change doesn't make sense, since L131 is inside an IF that checks if the major SMB version is 4... Checking if it is NOT 4 would simply always return false, and never execute the contained code, which is not what we need.

Try this, with the correct `TARGET_LIBDIR`:

```bash
echo ${TARGET_LIBDIR}
ls -l ${TARGET_LIBDIR}/samba/libsmbd_base*
```

In a previous comment, you said:
> '/usr/lib/x86_64-linux-gnu/samba/libsmbd-base-samba4.so': File exists

But the error `Error: missing dependent library libsmbd-base.so.0 (libsmbd-base-samba4.so)` says it doesn't exists.

You need to understand by the postinst script thinks it doesn't exist, if it does...

**Comment by robojerk** [comment] 2023-01-08 20:59
Here.
```
if [ -d /usr/lib/arm-linux-gnueabihf/samba/vfs ]; then
    SOURCE_LIBDIR="/usr/lib"
    TARGET_LIBDIR="/usr/lib/arm-linux-gnueabihf"
elif [ -d /usr/lib/x86_64-linux-gnu/samba/vfs ]; then
    SOURCE_LIBDIR="/usr/lib64" # Makefile will always install Greyhole .so files in /usr/lib64, for x86_64 CPUs. @see Makefile
    TARGET_LIBDIR="/usr/lib/x86_64-linux-gnu"
elif [ -d /usr/lib/i386-linux-gnu/samba/vfs ]; then
    SOURCE_LIBDIR="/usr/lib"
    TARGET_LIBDIR="/usr/lib/i386-linux-gnu"
elif [ "$(uname -m)" = "x86_64" ]; then
    SOURCE_LIBDIR="/usr/lib64"
    TARGET_LIBDIR="/usr/lib64"

    # For Ubuntu, where even x86_64 install use /usr/lib
    if [ -d /usr/lib/samba/vfs/ ]; then
        TARGET_LIBDIR="/usr/lib"
    fi
elif [ -d /usr/lib/aarch64-linux-gnu ]; then
    SOURCE_LIBDIR="/usr/lib/aarch64-linux-gnu"
    TARGET_LIBDIR="/usr/lib/aarch64-linux-gnu"
else
    SOURCE_LIBDIR="/usr/lib"
    TARGET_LIBDIR="/usr/lib"
fi
echo ${TARGET_LIBDIR}
ls -l ${TARGET_LIBDIR}/samba/libsmbd_base*
```
```
/usr/lib/x86_64-linux-gnu
ls: cannot access '/usr/lib/x86_64-linux-gnu/samba/libsmbd_base*': No such file or directory
```
Nothing with an underscore, but I do have files with a hyphen
```
/usr/lib/x86_64-linux-gnu
/usr/lib/x86_64-linux-gnu/samba/libsmbd-base-samba4.so -> /usr/share/greyhole/vfs-build/samba-4.16.4/bin/shared/private/libsmbd-base-samba4.so
/usr/lib/x86_64-linux-gnu/samba/libsmbd-base-samba4.so.0
```

**Comment by gboudreau** [comment] 2023-01-08 21:52
So the symbolic link to `/usr/share/greyhole` worked.

The only way I could see that L132 would think that `/usr/lib/x86_64-linux-gnu/samba/libsmbd-base-samba4.so` doesn't exist is if it is a symbolic link pointing to a file that doesn't exist...
You can test with:

```bash
TARGET_LIBDIR=/usr/lib/x86_64-linux-gnu
if [ ! -f ${TARGET_LIBDIR}/samba/libsmbd-base-samba4.so ]; then
    echo "Error: missing ${TARGET_LIBDIR}/samba/libsmbd-base-samba4.so"
    ls -l ${TARGET_LIBDIR}/samba/libsmbd-base-samba4.so
else
    echo "OK; file ${TARGET_LIBDIR}/samba/libsmbd-base-samba4.so exists"
fi
```

And since you already have a `libsmbd-base-samba4.so.0` file in that folder, you safest bet would be to create a symbolic link pointing to that...

```bash
cd ${TARGET_LIBDIR}/samba
rm libsmbd-base-samba4.so
ln -s libsmbd-base-samba4.so.0 libsmbd-base-samba4.so
```

**Comment by robojerk** [comment] 2023-01-08 22:34
Thank you...

I got it working..  

I did get a message when running apt install again
`ln: failed to create symbolic link '/usr/lib/x86_64-linux-gnu/samba/libsamba-debug-samba4.so': File exists`

I renamed that file to libsamba-debug-samba4.so.bak

tried again
apt install --reinstall greyhole
dpkg -i greyhole_0.15.18-1_amd64.deb

both threw a very generic, error

I uninstalled greyhole then resintalled (didnt save config sadface) and it installed fine finally, so hopefully no issues on the next upgrade.

Daemon appears to be running fine after adding my disks to the pool....

Thanks again.
