### ISSUE TITLE
Endless loop

### ISSUE THREAD

**Issue by PhilJung** [gboudreau/Greyhole#176] opened 2017-05-15 07:59 UTC
Hi,

Endless loop detected in the log:

  May 15 09:48:45 INFO write: /shares/Documents/A B/T/something.pdf doesn't exist anymore.
  May 15 09:48:45 INFO write: File created: Documents/A B/T/something.pdf
  May 15 09:48:45 INFO write:   /shares/Documents/A B/T/something.pdf doesn't exist anymore. Aborting.

greyhole --status always tells 
Currently working on task ID 8610229: write Documents/A B/T/something.pdf

Solved by:
DELETE FROM tasks WHERE id=8610229

Folder /shares/Documents/A B/ exists. Folder T doesn't exist inside A B

Greyhole version 0.10.6, Debian 8

**Comment by gboudreau** [comment] 2017-05-15 23:59
Can you reproduce with log_level = DEBUG ?

I can't reproduce; tried this:
```
mkdir A\B
mkdir A\ B/T ; echo 1> A\ B/T/something.pdf ; rm -rf /mnt/hdd2/shares/TimeMachine/A\ B/T
```

Result in greyhole.log:
```
May 15 19:57:59 DEBUG read_smb_spool: Directory created: TimeMachine/A B/T
May 15 19:57:59 DEBUG read_smb_spool: Found 1 new tasks in spool.
May 15 19:57:59 INFO write: Now working on task ID 3077720: write TimeMachine/A B/T/something.pdf
May 15 19:57:59 INFO write: /mnt/hdd2/shares/TimeMachine/A B/T/something.pdf doesn't exist anymore.
May 15 19:57:59 INFO write:   Skipping.
May 15 19:57:59 DEBUG sleep: Nothing to do... Sleeping.
```

**Comment by PhilJung** [comment] 2017-05-16 21:39
Hi, for the moment, the daemon is no longer locked. Will try if it happens again.

**Comment by jancoow** [comment] 2017-06-02 14:50
Hi. Got the same problem. Discovered it after the landing disk was full, turns out that greyhole is hanging in an endless loop for a couple of months.

**Comment by gboudreau** [comment] 2017-06-02 15:07
jancoow: can you send me the DEBUG logs that show the greyhole daemon trying to work on the same transaction over and over?

**Comment by jancoow** [comment] 2017-06-02 15:30
gboudreau: The debug log is about ~2,5gb . I can mail you a download link.

**Comment by gboudreau** [comment] 2017-06-02 15:34
@jancoow Maybe try to find a unique filename in that, and do this:

```
grep -B 100 -A 100 "unique_file_name" /var/log/greyhole.log | tail -10000 > ~/sample_greyhole.log
```

**Comment by jancoow** [comment] 2017-06-02 15:46
@gboudreau 
Thanks, these files were in a loop today. 
The file "Adobe.vbox-tmp" and the dir "BOOT" didn't exist anymore on the disk. 

[greyhole_loop.txt](https://github.com/gboudreau/Greyhole/files/1048165/greyhole_loop.txt)

**Comment by sosojni** [comment] 2017-06-19 12:43
Happened to me more than few times. Always fixed by deleting task that was looping. Ill try and catch good logs next time.

**Comment by jancoow** [comment] 2017-06-29 13:27
Again I got stuck in an endless loop. Is there already a solution for this problem?

**Comment by sosojni** [comment] 2017-06-29 13:40
Happened to mee too few days ago, but again, no good logs available. I noticed it happens in times when tehere are a lot of small files created on LZ. If they are created and deleted too fast, loop sometimes happens. Most of my problems were caused by temp files that MAC users create when unzipping files. I have inserted some ignore filters for it and im hoping it will fix my problem. For now, all good.

**Comment by jancoow** [comment] 2017-06-29 14:10
@sosojni Did you saw my log files? 
I think what you are saying is right. It mostly happends with temp files, which are deleted fast. 
I'm currently having this issue, so if you want any additional log files I could post them.

**Comment by gboudreau** [comment] 2017-06-29 19:03
@jancoow If you can provide me with SSH & sudo access, I could debug the problem on your server.
If you need, I can give you connection details for you to create a SSH reverse-tunnel to your server, so you don't have to setup port-forwarding on your router.
Just open a ticket on https://greyhole.freshdesk.com to talk in private.

**Comment by jancoow** [comment] 2017-06-29 20:30
@gboudreau 
Hi. I created a ticket on freshdesk. If could also talk on IRC if you prefer.

**Closed** 2017-06-29 22:29 UTC

**Comment by gboudreau** [comment] 2017-06-29 22:30
OK, found the issue. Your server is using a non-compiled version of greyhole that has the fix, and it's working on the backlog right now.
Will build a new 0.10.11 version that will contain the fix now.

**Comment by gboudreau** [comment] 2017-06-29 22:37
You got 0.10.11 running on your server. That should resolve this (very nasty) issue.
@sosojni please update and comment here if the issue occurs again after updating.

Thanks for your patience guys.

**Comment by sosojni** [comment] 2017-06-30 19:25
Thank you very much, i will update as soon as possible (currently away from server) and ill report here after some time

**Comment by sosojni** [comment] 2017-07-03 10:17
Finally able to give look at the server. Endless loop was waiting for me. I updated and endles loop was brokend and process continued as usual. I think you did it! Thanks!

**Comment by jancoow** [comment] 2017-07-03 10:31
@gboudreau Thank you very much! It's working great again!
